### ISSUE TITLE
dim locations

### ISSUE THREAD

**Issue by iacopoff** [IRPIhydrology/SM2RAIN_ASCAT_reader#1]
Hi, 
if I may, I was wondering what is the reason to have a data structure with "locations" as dimension and not "latitude" and "longitude".
 
` ncdump -h SM2RAIN_ASCAT_0125_2007.nc
netcdf SM2RAIN_ASCAT_0125_2007 {
dimensions:
        time = 365 ;
        locations = 839826 ;
variables:
        float Time(time) ;
                Time:long_name = "Time of measurement" ;
                Time:standard_name = "Time" ;
                Time:units = "Days since 1-Jan-2000" ;
        float Longitude(locations) ;
                Longitude:long_name = "location longitude" ;
                Longitude:standard_name = "Longitude" ;
                Longitude:units = "degrees_east" ;
                Longitude:valid_range = -180., 180. ;
        float Latitude(locations) ;
                Latitude:long_name = "location latitude" ;
                Latitude:standard_name = "Latitude" ;
                Latitude:units = "degrees_north" ;
                Latitude:valid_range = -90., 90. ;
        float Rainfall(locations, time) ;
                Rainfall:_FillValue = -9999.f ;
                Rainfall:long_name = "Daily rainfall in mm" ;
                Rainfall:standard_name = "Daily rainfall" ;
                Rainfall:units = "mm/day" ;
        byte Conf_flag(locations) ;
                Conf_flag:long_name = "Confidence flag" ;
                Conf_flag:flag_meanings = "Low_quality_SM Topographic_complexity>30% Bad_surface_state_flag" ;
                Conf_flag:flag_masks = 1., 2., 4. ;
                Conf_flag:valid_range = 0., 7. ;
        byte ssf(locations, time) ;
                ssf:long_name = "surface state flag based on ERA5 soil temperature" ;
                ssf:standard_name = "surface state flag" ;
                ssf:flag_meanings = "unfrozen frozen_temporary frozen" ;
                ssf:flag_masks = 0., 1., 2. ;
                ssf:valid_range = 0., 2. ;

// global attributes:
                :title = "ASCAT Soil moisture-derived rainfall using SM2RAIN" ;
                :creation_time = "13-Mar-2019 08:47:06" ;
                :creator_institution = "National Research Council  - Research Institute for Geo-hydrological Protection (CNR-IRPI)" ;
                :creator_institution_e-mail = "idrologia@irpi.cnr.it" ;
                :calibration = "Two different calibration has been performed using as benchmark model data from ERA5, for the data before and after 2013 (because of the introduction of Metop-B)." ;
                :correction = "A climatological adjustment using model data from ERA5 have been applied to the dataset, using the monthly data between 2000 and 2018" ;
                :Temporal_interval = "Jan-01-2007 to Dec-31-2007" ;
                :Acknowledgements = "Global SM2RAIN project (contract n.EUM/CO/17/4600001981/BBo)" ;
}
`

thanks,

iacopo

**Comment by lucabrocca78** [comment]
Data are stored as time series at multiple locations as the grid is irregular and only available over land
